### ISSUE TITLE
Doesn't work when binded with multiple functions.

### ISSUE THREAD

**Issue by Greenish-toast** [dukimi/locationcopy#1]
I've got the mod and a quick disconnect mod both bound to the same key (Backspace) and instead of copying location and disconnecting it just copies the location, I've tested using other mods that are fine with being bound with multiple mods and even then it doesn't work! Please fix this or at least tell me if it isn't possible because this is a really useful mod combination on things like anarchy or just if you're clumsy and fell into lava..

**Comment by dukimi** [comment]
> I've got the mod and a quick disconnect mod both bound to the same key (Backspace) and instead of copying location and disconnecting it just copies the location, I've tested using other mods that are fine with being bound with multiple mods and even then it doesn't work! Please fix this or at least tell me if it isn't possible because this is a really useful mod combination on things like anarchy or just if you're clumsy and fell into lava..

If you are using the same keybind as Location Copy with other mods, there is a high probability that there will be a error with those mods and the feature will not work. I recommend setting all mods to use different keys, including Location Copy, to avoid error whenever possible. However, the error with other mods is unexpected, and I'll see what I can do about it. Thanks for using my mod:)
