### ISSUE TITLE
Edit message translation

### ISSUE THREAD

**Issue by Xm4g1kZzXj0k3** [dukimi/locationcopy#2]
Hi,
i would purpose you to add a feature that permit to modify the message that is sent when copy the location.

![immagine](https://github.com/user-attachments/assets/46516eb6-1843-4e6b-a8db-6a92bc574fb8)

**Comment by dukimi** [comment]
Hello!

Thank you for suggesting additional features!

If you want to modify the message you are showing now, you can modify it directly from the language file in the mod, as in the picture.
![picture](https://github.com/user-attachments/assets/a2d0ef02-2e9f-44b0-95bc-57cbf475b5e5)
![image](https://github.com/user-attachments/assets/5b8d94bf-f6a5-41c4-be52-a170744d2582)


But let's consider adding a feature that allows you to modify your messages directly through the UI in the game.

Thank you for using my mod!

**Comment by Xm4g1kZzXj0k3** [comment]
Thank you.
👍
